[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_dao = "6kcfzoGSjT4EqX9UHzwPw5UET9hVrYuA2LERx2Po33i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ayomideaderojuola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
